[build]
command = "npm run build"
functions = "dist/server"
publish = "dist/client"

[functions]
directory = "dist/server"
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
